### ISSUE TITLE
Training/React: Charts

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#156]
Contains all issues related to polishing all nine of the React Chart tutorials for 12/18 release

**Comment by christiemolloy** [comment]
**Overall Chart Feedback:** this will be added to so don't implement yet.

- [ ] This sentence needs clarification: what is a "collection of React based components"?
- [ ] Remove all instances of "we'll"
- [ ] Remove all steps that don't have action.

**Comment by christiemolloy** [comment]
Closing this because this has been addressed.
