### ISSUE TITLE
Training/HTMLCSS: Variable Naming Principles

### ISSUE THREAD

**Issue by christiemolloy** [patternfly/training-scenarios#158]
Contains all issues related to polishing HTML/CSS BEM Naming Principles tutorials for 12/18 release

**Comment by christiemolloy** [comment]
**Overall**

- [ ] More instructions related to how to type in the variable name
- [ ] Add instructions to demonstrate that when you make changes in the editor, you won't see any visible changes in the iframe
- [ ] Make all steps actionable
